{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.libxposed",
    "module": "api",
    "version": "100",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-100.aar",
          "url": "api-100.aar",
          "size": 16213,
          "sha512": "d45212be516a1e7a87ad692edaeb02fcda670f2ad6251fd55aae02f302fd1174eb8e4e6a22a324ae57c92e1c64199e97c87e22e260a2e26e75e89d6d9f34ceb9",
          "sha256": "cc2f1f8483c0fe0f9e4ff57eacf8f6caa71fc1394bb1f2f4c63524e6011d4a31",
          "sha1": "bbaaf0ee195c3788946ae51ecd82ae91ec579562",
          "md5": "269712431ceb53f7c9fb53ecf2ffa13f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100.aar",
          "url": "api-100.aar",
          "size": 16213,
          "sha512": "d45212be516a1e7a87ad692edaeb02fcda670f2ad6251fd55aae02f302fd1174eb8e4e6a22a324ae57c92e1c64199e97c87e22e260a2e26e75e89d6d9f34ceb9",
          "sha256": "cc2f1f8483c0fe0f9e4ff57eacf8f6caa71fc1394bb1f2f4c63524e6011d4a31",
          "sha1": "bbaaf0ee195c3788946ae51ecd82ae91ec579562",
          "md5": "269712431ceb53f7c9fb53ecf2ffa13f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100-sources.jar",
          "url": "api-100-sources.jar",
          "size": 10244,
          "sha512": "4823fb19b83fab2fcf6de7b9357b3da7407015ec45b7783eb49fab52614c98d327145de3bc4357b6345b82dbe3a622855c0602096ee431636d8ce199f79db5e9",
          "sha256": "725334825579012d8dc678bcfca49e1923ada14a7744e3595e74a8efe8261a65",
          "sha1": "7c41e80d64aed490440c30bb660ab9867c003540",
          "md5": "3674e59f9a64606c70d1ec03235f663c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100-javadoc.jar",
          "url": "api-100-javadoc.jar",
          "size": 394661,
          "sha512": "537d53679674d8a062704e5067a3d342d97406e099caf4f46ee97c12301afb4f4edb8adc5d2d51497fd14cc41781d95c1fd3f51472ece41ed94e8aa72dc04d3d",
          "sha256": "85756989926d288f7824ec891bd03830582fdecf22650726fc1e2542f096d0be",
          "sha1": "71bfea63e099455805fe59d1c7459c5dd2456f5b",
          "md5": "a421ac5536a74be9c4d208d3f7792c45"
        }
      ]
    }
  ]
}
